name: ews
description: A Dart client library to access Microsoft Exchange web services. The library works against Office 365 Exchange Online as well as on premises Exchange.
version: 2.0.0
author: Dmytro Glynskyi <dmytro.glynskyi@gmail.com>
homepage: https://github.com/glynskyi/ews

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.8.1
  xml: ^5.1.2
  synchronized: ^3.0.0
  intl: ^0.17.0
  timezone: ^0.7.0
  uuid: ^3.0.4
  collection: ^1.15.0

dev_dependencies:
  test: ^1.17.10
  pedantic: ^1.11.0