name: ews
description: A Dart client library to access Microsoft Exchange web services. The library works against Office 365 Exchange Online as well as on premises Exchange.
version: 0.0.13
author: Dmytro Glynskyi <dmytro.glynskyi@gmail.com>
homepage: https://github.com/glynskyi/ews

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  xml: ^3.5.0
  synchronized: ^2.1.0+1
  uuid_enhanced: ^3.0.2
  intl: ^0.16.0
  timezone: ^0.5.5

dev_dependencies:
  test: ^1.9.3
  dotenv: ^1.0.0