name: ews
description: A Dart client library to access Microsoft Exchange web services. The library works against Office 365 Exchange Online as well as on premises Exchange.
version: 1.1.8
author: Dmytro Glynskyi <dmytro.glynskyi@gmail.com>
homepage: https://github.com/glynskyi/ews

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  xml: ^5.0.0-nullsafety
  synchronized: ^3.0.0-nullsafety
  intl: ^0.17.0-nullsafety
  timezone: ^0.7.0-nullsafety

dev_dependencies:
  test: ^1.16.0-nullsafety