name: ews
description: A Dart client library to access Microsoft Exchange web services. The library works against Office 365 Exchange Online as well as on premises Exchange.
version: 1.2.0-nullsafety.4
author: Dmytro Glynskyi <dmytro.glynskyi@gmail.com>
homepage: https://github.com/glynskyi/ews

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  xml: ^5.0.1
  synchronized: ^3.0.0
  intl: ^0.17.0
  timezone: ^0.7.0-nullsafety
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.3
  pedantic: ^1.10.0